services:
  backend:
    image: thenu8175/cloudops-dashboard-backend:latest
    container_name: cloudops-backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: thenu8175/cloudops-dashboard-frontend:latest
    container_name: cloudops-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped