name: CloudOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      
      # Docker Login

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      
      # Backend Image

      - name: Build Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            thenu8175/cloudops-dashboard-backend:${{ github.sha }}
            thenu8175/cloudops-dashboard-backend:latest

            
      # Frontend Image

      - name: Build Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            thenu8175/cloudops-dashboard-frontend:${{ github.sha }}
            thenu8175/cloudops-dashboard-frontend:latest

    
      # Clone GitOps Repository

      - name: Clone GitOps Repository
        run: |
          git clone https://${{ secrets.GITOPS_USERNAME }}:${{ secrets.GITOPS_TOKEN }}@github.com/${{ secrets.GITOPS_USERNAME }}/cloudops-dashboard-gitops.git

    
      # Update Backend Image
      
      - name: Update Backend Image
        run: |
          sed -i "s|image: thenu8175/cloudops-dashboard-backend:.*|image: thenu8175/cloudops-dashboard-backend:${{ github.sha }}|" cloudops-dashboard-gitops/k8s/backend/backend.yaml

      
      # Update Frontend Image
      
      - name: Update Frontend Image
        run: |
          sed -i "s|image: thenu8175/cloudops-dashboard-frontend:.*|image: thenu8175/cloudops-dashboard-frontend:${{ github.sha }}|" cloudops-dashboard-gitops/k8s/frontend/frontend.yaml

      
      # Commit Changes
      
      - name: Commit Changes
        run: |
          cd cloudops-dashboard-gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git diff --cached --quiet || git commit -m "Update images to ${{ github.sha }}"

          git push